language: ruby
rvm:
  - 1.8.7
  - ree
  - 2.0.0
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails2_3_8.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails4.gemfile